### ISSUE TITLE
Exception in Task retrieval

### ISSUE THREAD

**Issue by trevor256** [TobyMarch/1TaaT#50]
https://github.com/TobyMarch/1TaaT/tree/front

![image](https://github.com/TobyMarch/1TaaT/assets/79394682/f73690be-244e-46a0-8bcc-06539bdafe18)

```
024-04-26T15:16:29.656-04:00  WARN 9048 --- [nio-8080-exec-2] c.t.t.controllers.TaskController         : Exception in Top Task retrieval: 

org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.time.Instant] for value []
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[spring-core-6.1.3.jar:6.1.3]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:182) ~[spring-core-6.1.3.jar:6.1.3]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:165) ~[spring-core-6.1.3.jar:6.1.3]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.doConvert(MappingMongoConverter.java:1829) ~[spring-data-mongodb-4.2.2.jar:4.2.2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.doConvert(MappingMongoConverter.java:1821) ~[spring-data-mongodb-4.2.2.jar:4.2.2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1346) ~[spring-data-mongodb-4.2.2.jar:4.2.2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter.getPotentiallyConvertedSimpleRead(MappingMongoConverter.java:1331) ~[spring-data-mongodb-4.2.2.jar:4.2.2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$DefaultConversionContext.convert(MappingMongoConverter.java:2327) ~[spring-data-mongodb-4.2.2.jar:4.2.2]
	at org.springframework.data.mongodb.core.convert.MappingMongoConverter$ConversionContext.convert(MappingMongoConverter.java:2175) ~[spring-data-mongodb-4.2.2.jar:4.2.2]

```

**Comment by trevor256** [comment]
I'm getting, the TimeDate issue again that's not allowing tasks to be pulled I think? I'm having a hard time figuring out.

**Comment by TobyMarch** [comment]
What's your userID? And did you insert any specific Tasks before this error occurred?

**Comment by trevor256** [comment]
106946643108395921868  , and I must have? It was working fine and then it started happening. I don't think anything changed about the time formats.

**Comment by trevor256** [comment]
does running [ps://github.com/TobyMarch/1TaaT/tree/front](https://github.com/TobyMarch/1TaaT/tree/front) work for you?

**Comment by trevor256** [comment]
problem was caused by 
const [duration, setDuration] = useState("S"); 
was set to 1 instead of S
